name: deploy

on: 
  push:
    branches:
    - 'source'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Ruby Versions
      run: ls $RUNNER_TOOL_CACHE/Ruby
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: Cache Ruby Gems
      uses: actions/cache@v1
      with:
        path: "$RUNNER_TOOL_CACHE/Ruby/2.5.7/x64/"
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bootstrap
      run: make bootstrap
    - name: Build
      run: make test
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        # Depending on the repository permissions you may need to provide 
        #  the action with a GitHub personal access token instead of the 
        #  provided GitHub token in order to deploy. This should be stored as a secret.
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # This is the branch you wish to deploy to, for example gh-pages or docs.
        BRANCH: 'master'
        # The folder in your repository that you want to deploy. 
        #  If your build script compiles into a directory named build you would put it here. 
        #  Folder paths cannot have a leading / or ./. 
        #  If you wish to deploy the root directory you can place a . here.
        FOLDER: 'build'
