name: verify_pull_request

on: 
  pull_request:
    branches-ignore:
    - 'master'  # ignore pushes to master, because we publish our website there

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Ruby Versions
      run: ls $RUNNER_TOOL_CACHE/Ruby
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: Cache Ruby Gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bootstrap
      run: |
        bundle config path vendor/bundle
        make bootstrap
    - name: Build
      run: make test
